### ISSUE TITLE
snort failed to verdict reset with small file.

### ISSUE THREAD

**Issue by freedai** [snortadmin/snort3#11]
Snort-3.0.0-a4-213.
When I set reset for EICAR.COM, I can download that file and I didn't see signature_lookup got triggered. The file is very small and just 69 bytes. reset avast_free_antivirus_setup_online.ext works fine.

```
file_id =
{
    enable_type = true,
    enable_signature = true,
    file_rules = file_magic,
    enable_capture = true,
    type_depth = 104857600,
    signature_depth = 104857600,
    capture_max_size = 104857600,
    trace_type = true,
    trace_signature = true,
    file_policy =
    {
        -- http://10.50.8.202/pkgs/virus/avast_free_antivirus_setup_online.exe
        { when = {sha256 = "7ea883d91f36d26166751e05d734571a561312fbd078068787ad3efac2bcb0e6"}, use = {verdict = 'reset' } },
        -- http://10.50.8.202/pkgs/virus/EICAR.COM
        { when = {sha256 = "131f95c51cc819465fa1797f6ccacf9d494aaaff46fa3eac73ae63ffbdfd8267"}, use = {verdict = 'reset' } }
    },
}
```

**Comment by huicao** [comment]
Hi Freda,

Thanks for the info. This is a bug we will address in the future release.

Best,
Hui.

**Comment by freedai** [comment]
Thanks Hui. Do you know what's the smallest file size that will have this scenario?

**Comment by huicao** [comment]
We have this supported in old http_server inspector. However, there is an issue for http_inpect. The resume blocking has not been integrated with this new http inspector yet.

File size won't matter that much.

Best,
Hui.

**Comment by freedai** [comment]
Hello Hui,

You are correct. File size doesn't matter. It's the issue that file type is always enabled regardless the setup in snort.lua. I have to define file type for EICAR.COM in order to make signature work. I created pull request https://github.com/snortadmin/snort3/pull/15 for this.

Thanks.

**Comment by snortadmin** [comment]
@huicao - will this be fixed in Alpha 4?

**Comment by snortadmin** [comment]
FYI - this was fixed a few builds back (220 I think).
