### ISSUE TITLE
incomplete figures in snort_manual.pdf

### ISSUE THREAD

**Issue by wyatuestc** [snortadmin/snort3#13]
page 5 and 6

![12](https://cloud.githubusercontent.com/assets/3883941/20253305/17900c9a-aa65-11e6-9756-c49a88a64cd3.jpg)

![13](https://cloud.githubusercontent.com/assets/3883941/20253306/18743bfe-aa65-11e6-921e-1a5a404fe606.jpg)

**Comment by snortadmin** [comment]
What exactly is the issue you are raising?

**Comment by wyatuestc** [comment]
If you open the file snort_manual.pdf, you will find that figures in page 5 and page 6 are incomplete.

page 5
![snort2](https://cloud.githubusercontent.com/assets/3883941/20272884/4f13fbda-aaca-11e6-88f2-6407ff90e5cf.jpg)

![snort2x](https://cloud.githubusercontent.com/assets/3883941/20273027/c4efe314-aaca-11e6-8722-1aeaf0ac187b.png)

page 6
![snort3](https://cloud.githubusercontent.com/assets/3883941/20272885/508be752-aaca-11e6-88a4-4fdcc41b5ad4.jpg)

![snort3x](https://cloud.githubusercontent.com/assets/3883941/20273030/c6ac01ec-aaca-11e6-8aa2-d2a6cd616fd8.png)

Maybe we should modify something to make sure those figures properly in the pdf.

**Comment by snortadmin** [comment]
Thanks - I thought the clipping was your copy / paste.  I guess those can be cut down from 640 to 480 unless there is a better way with %width or something.

**Comment by snortadmin** [comment]
Cut it down to 480 and it looks good to me.  Thanks for reporting the issue.
