### ISSUE TITLE
Snort logging to file

### ISSUE THREAD

**Issue by Philelis** [snortadmin/snort3#21]
Hey,
I am running snort3 on CentOS 7 and wanted to log the messages to a normal file. I tried several things and I only see it on stdout or with syslog. My last try was this one:
`
 snort -c /etc/snort/config/snort.lua -i eth0 -l /var/log/snort -A alert_csv -D `

Does anyone have the same issues? Or a solution for me?

**Comment by snortadmin** [comment]
You can see the available configuration like this:

     $ snort --help-config alert_csv

That output includes this line:

     bool alert_csv.file = false: output to alert_csv.txt instead of stdout

So if you add this to your conf:

     alert_csv = { file = true }

Or add this to your command line:

     --lua "alert_csv = { file = true }"

You will write to file.  See the user manual for how to control file 
path and name.

**Comment by Philelis** [comment]
Thanks a lot, the second version worked for me. First not, I think I put it on a false position.

**Comment by blendajazi** [comment]
thanks guys. worked for me too
