### ISSUE TITLE
Where to report bugs

### ISSUE THREAD

**Issue by bshastry** [snortadmin/snort3#22]
Hi,

I have been testing snort3 and have managed to find program crashes in read pcap mode. Where do I report them?

Thanks!
Bhargava

**Comment by bshastry** [comment]
Oops, didn't read carefully enough. They need to be sent to `bugs@snort.org`

Sorry!

**Comment by snortadmin** [comment]
Feel free to report on Snort++ issues here.  We check both.  We will follow up on this one at bugs@.  Thanks.

**Comment by bshastry** [comment]
Mailed a report to `bugs@snort.org`. Waiting on your acknowledgement :-)

**Comment by bshastry** [comment]
Heho, re-opening since I didn't get a response from `bugs@snort.org`

**Comment by snortadmin** [comment]
Oops, my email only went to back to bugs@.  I asked this:

"That's an eth:icmp6 packet, which should be illegal, so our fix would be to fail to decode and drop when inline.  Did you craft or capture your pcap?"

We have a fix that will be out later today or early next week on github.

**Comment by bshastry** [comment]
No worries. Shall I initiate a CVE for this or do you have a security process that already takes this into account?

The reason I ask is that FOSS projects differ in how they handle security bugs. I would like to know what snort's view is.

**Comment by snortadmin** [comment]
Actually that packet is eth:llc:snap:invalid but due to the Snort++ implementation and a bug in the llc codec (which includes the snap header) it looks to Snort++ like icmp6 and hence the crash.

We have a process.  Someone will be contacting you.  Thanks.

**Comment by snortadmin** [comment]
This issue was fixed.  The packet manager now does validation of the ether type and will raise 116:473, (decode) ether type out of range as appropriate.
