### ISSUE TITLE
snort++ using file magic for capture file from http traffic

### ISSUE THREAD

**Issue by androuxx** [snortadmin/snort3#3]
hi,
i build snort++  on my ubuntu server, but there is no clarification about the snort.lua configuration
how i can use the file magic features ? and how can i specify the output format and path ?
and in snort 2.9.x we can set output path for each rules using ruletype option but there is no option for that in snort++ 
also i use snort2lua to convert my snort.conf to snort.lua and he does't take all option in .conf file like output format and ruletype
where i can get full snort.lua file ?

**Comment by snortadmin** [comment]
On 4/23/16 11:42 AM, androuxx wrote:
>
> hi,
> i build snort++ on my ubuntu server, but there is no clarification 
> about the snort.lua configuration
> how i can use the file magic features ?
>
The default snort.lua includes the default file_magic.lua and enables it 
with file_id.  Make sure you have the latest (git clone 
https://github.com/snortadmin/snort3.git).  There are lots of 
configuration options in the user manual or do

     snort --help-module file_id
>
> and how can i specify the output format and path ?
>
Output of what?
>
> and in snort 2.9.x we can set output path for each rules using 
> ruletype option but there is no option for that in snort++
> also i use snort2lua to convert my snort.conf to snort.lua and he 
> does't take all option in .conf file like output format and ruletype
> where i can get full snort.lua file ?
>
ruletype is not supported directly.  What exactly are you trying to do?

The default config is in etc/:

     etc/snort.lua
     etc/snort_defaults.lua
     etc/file_magic.lua

For simplicity, internal defaults are not explicitly specified those 
files.  But there are many ways to see them.  Check the user manual or 
run this command to get an overview of the command line help available:

     snort --help

**Comment by androuxx** [comment]
Exactly I'm trying to extract each rule/alert output to a single directory , that is usually done in 2.9.x by defining ruletype (custom action). In addition, the output format can be set in 2.9.x to pcap format instead of raw Unified2, in 3.0 the following cofiguration dosn't work as expected , 
output = 
{
logdir = '/var/log/snort3',
}
log_pcap =
{
  limit = 4,
  units = M,
}
the following command is used to run snort :  snort -i eth0 -c /etc/snort3/snort.lua -R /etc/snort3/new.rules
and the rule used for testing purpose : alert tcp any any -> any any (msg:"connection"; sid:1003; rev:1;)
** pcap files does not apear at all in '/var/log/snort3' , any ideas ?**

**Comment by snortadmin** [comment]
The only thing apparently wrong with your config is that units is a 
string so should be units = 'M'.

Some other things worth noting:

-- log_pcap is only going to log raw packets.  Unlike Snort, alerts on 
reassembled data don't have an associated packet.  We could log the 
triggering packet but that won't always have the relevant content.

-- You could write an any-any rule like this:

     alert tcp (msg:"connection"; sid:1003; rev:1;)

Another question:  were you using ruletype to log alerts for each rule 
to a separate directory or were all going to the same directory?

**Comment by androuxx** [comment]
as you told me before that the ruletype was not support on snort++ so i
never use it
how can i user the snort magic rules to capture the files from the network ?
i try it but the output file was not open , it's give me corrupted file "
tested on .pdf files"

could you please send a working configuration that achieve the following:
include the file magic for capture the file extension "pdf,doc, ppt ..."
the output  for the file magic and the size ".pcap"

**Comment by huicao** [comment]
Hi Androuxx,

Please add the following into your config file:

file_id = {
     enable_type = true,
     enable_signature = true,
     enable_capture = true,
     file_rules = file_magic,
     type_depth = 56384,
     capture_max_size = 10485760,
}

file magics are in lua/file_magic.lua


Best,
Hui.

**Comment by androuxx** [comment]
thank you for your attention
the file magic working, but the output of the files named by sha256, so how
can i know the name of the file and the network information of it ( source
ip, destination ip, url ,etc..)



​

**Comment by huicao** [comment]
This will be supported in the future release.

Best,
Hui.

**Comment by snortadmin** [comment]
Re "as you told me before that the ruletype was not support on snort++ so i
never use it"

I was asking why exactly you used it with Snort 2.X so that I can ensure that the use case is satisfied with Snort++.

**Comment by androuxx** [comment]
i use ruletype in snort 2.X as following:  
```
ruletype http_traffic
{
  type log
   output log_tcpdump: /var/log/snort/http_traffic/snort.http_traffic 1024M
}

```
for rules: 
`http_traffict tcp $HOME_NET any -> any $HTTP_PORT (msg:"HTTP_TRAFFIC";sid:1000008;rev:1;)`

for capture all http traffic in single directory 
and the  same for the dns  traffic or other types
so i use ruletype for set output files for each rule used in my company

**Comment by snortadmin** [comment]
OK so you try to log separate pcaps for each rule.  Is that so you can more easily correlate pcaps to events?  Have you tried using unified2 output?

**Comment by androuxx** [comment]
yes , I used ruletype to separate each of http/ dns / ......   logs in  separate pcap or u2 files , is their any work around in snort 3 to achieve the same results ?

**Comment by snortadmin** [comment]
Not presently.  Log file is based on type of logger and packet thread and related naming options.

**Comment by snortadmin** [comment]
I am closing this issue.  Please open another issue for anything specific.  Thanks all.
