### ISSUE TITLE
Missing building configure setup

### ISSUE THREAD

**Issue by windhamwong** [snortadmin/snort3#37]
The command `./configure` throws error of Cannot find install-sh, install.sh, or shtool in ac-aux.
The issue can be solved by running

> libtoolize --force
> aclocal
> autoheader
> automake --force-missing --add-missing
> autoconf
> ./configure

I am wondering can we include this in README or a automake script to run before `./configure`?
Reference: https://askubuntu.com/questions/27677/cannot-find-install-sh-install-sh-or-shtool-in-ac-aux

**Comment by snortadmin** [comment]
Hi, thanks for reporting the issue.  What steps led to this error?  There is no ./configure if you clone from this repo and you should do autoreconf -isvf to generate it (and other build foo).  This is mentioned in the README.  Did you follow those steps?

**Comment by windhamwong** [comment]
Oh thanks, i think this is my mistake then.

**Comment by snortadmin** [comment]
OK thanks.
