### ISSUE TITLE
Shell for config Snort

### ISSUE THREAD

**Issue by M3nin0** [snortadmin/snort3#4]
I am creating a script to facilitate the configuration of Snort if someone wants to help.
https://github.com/M3nin0/Snort-Config

I'm not very good with shell then not to call errors

Thanks =D

**Comment by snortadmin** [comment]
Hi - thanks for sharing your work.  Your scripts are for Snort 2.X though.  This project is Snort++, for version 3.0 work.  Please direct your query to snort-users@lists.sourceforge.net.
