### ISSUE TITLE
inspector data_log file_log did not working

### ISSUE THREAD

**Issue by yhaomin** [snortadmin/snort3#40]
inspector data_log file_log did not working.How can I fix it?
extra plugins have been installed and run snort with data_log using --plugin-path /data/snort/lib/snort_extra
inspector appids  seems working well because alert occurs when testing appids using rule "alert http (msg:"http"; sid:1000000001;)".
data.log and file.log have been created in the expected location.

1. Snort Version
   ,,_     -*> Snort++ <*-
  o"  )~   Version 3.0.0-a4 (Build 239) from 2.9.8-383
   ''''    By Martin Roesch & The Snort Team
           http://snort.org/contact#team
           Copyright (C) 2014-2017 Cisco and/or its affiliates. All rights reserved.
           Copyright (C) 1998-2013 Sourcefire, Inc., et al.
           Using DAQ version 2.2.2
           Using libpcap version 1.5.3
           Using LuaJIT version 2.0.4
           Using PCRE version 8.32 2012-11-30
           Using ZLIB version 1.2.7
           Using LZMA version 5.1.2alpha
           Using OpenSSL 1.0.1e-fips 17 Nov 2016

2. snort config
data_log = { key = 'http_raw_uri' }
file_log = { log_pkt_time = true, log_sys_time = false }

3. base Statistics
file type stats (files)
         Type              Download   Upload 
        RIFF( 24)          5          0          
         GIF( 62)          1          0          
         GIF( 63)          32         0          
         PNG( 69)          42         0          
        JPEG( 70)          43         0          
        JPEG(157)          55         0          
            Total          178        0   
http_inspect
                    flows: 172
                    scans: 2219
              reassembles: 6985
              inspections: 1926
                 requests: 316
                responses: 313
             get_requests: 316
                  chunked: 51
       uri_normalizations: 24
               uri_coding: 10

**Comment by snortadmin** [comment]
That data_log config should produce this error:

ERROR: invalid data_log.key = 'http_raw_uri'
FATAL: see prior 1 errors (0 warnings)
Fatal Error, Quitting..

To see the valid options for data_log.key, do this:

$ src/snort --plugin-path $SNORT_PLUGIN_PATH --help-config data_log | grep key
select data_log.key = http_request_header_event : name of the event to log { http_request_header_event | http_response_header_event }
