### ISSUE TITLE
can't running snort, error libluajit 

### ISSUE THREAD

**Issue by arifkhumaidi-** [snortadmin/snort3#6]
$firewall/bin/snort --help
/usr/local/src/snort/bin/snort: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

**Comment by jncornett** [comment]
What happens when you run `ldd` on the binary?

**Comment by arifkhumaidi-** [comment]
i got this.. when running ldd on the bin
![testing uplo](https://cloud.githubusercontent.com/assets/10564974/15200479/861fc3bc-1811-11e6-8052-70104fb0e54d.jpg)

**Comment by jncornett** [comment]
Ok try symlinking libluajit to a location in your library search path. `ln -s $path/to/libluajit /usr/lib/x86_64-linux-gnu`

 For future reference, copying and pasting the text output is greatly preferred to screenshots

**Comment by arifkhumaidi-** [comment]
Its running... thank's @jncornett 

> For future reference, copying and pasting the text output is greatly preferred to screenshots
ok, i will
